<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
	  <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="33.1.0" />
    <PackageReference Include="EPPlus" Version="6.2.10" />
    <PackageReference Include="Microsoft.Office.Interop.Excel" Version="16.0.18925.20022">
      <IncludeAssets>all</IncludeAssets>
      <PrivateAssets>none</PrivateAssets>
    </PackageReference>
    <PackageReference Include="NuGet.Packaging" Version="6.14.0" />
    <PackageReference Include="WinForms.DataVisualization" Version="1.10.0" />
  </ItemGroup>

  <PropertyGroup>
    <!-- Add Office installation directory to assembly probing paths -->
    <AssemblyProbingPaths>$(AssemblyProbingPaths);C:\Program Files\Microsoft Office\root\Office16</AssemblyProbingPaths>
  </PropertyGroup>

  <Target Name="CopyOfficeDll" AfterTargets="Build" Condition="Exists('C:\WINDOWS\assembly\GAC_MSIL\office\15.0.0.0__71e9bce111e9429c\office.dll')">
    <Copy SourceFiles="C:\WINDOWS\assembly\GAC_MSIL\office\15.0.0.0__71e9bce111e9429c\office.dll" 
          DestinationFolder="$(OutputPath)" 
          SkipUnchangedFiles="true" />
  </Target>

  <ItemGroup>
    <None Update="bakery_sales_cleaned.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\bakery_sales_cleaned_locations.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="app.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>